import streamlit as st
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
import tempfile
import os
from datetime import datetime

st.set_page_config(page_title="Auto FIR Generator", layout="wide")

st.title("AI Auto FIR Generator")
st.markdown("Generate cybercrime complaint reports from scam messages")

# =========================
# FIR GENERATOR FUNCTION
# =========================
def generate_fir(text):

    time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    fir_text = f"""
CYBER CRIME COMPLAINT REPORT

Date & Time: {time}

Complaint Type: Digital Fraud / Scam Attempt

Incident Description:
{text}

Suspected Modus Operandi:
- Impersonation of authority (Police / CBI / Bank)
- Financial manipulation attempt
- Psychological pressure tactics
- Digital communication fraud

Recommendation:
Immediate investigation required by Cyber Crime Cell.
Account freezing and number tracing recommended.

Disclaimer:
This report is auto-generated by AI Fraud Detection System.
"""

    return fir_text

# =========================
# PDF CREATION
# =========================
def create_pdf(content):

    file_path = os.path.join(tempfile.gettempdir(), "FIR_Report.pdf")

    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()

    story = []

    for line in content.split("\n"):
        story.append(Paragraph(line, styles["Normal"]))
        story.append(Spacer(1, 8))

    doc.build(story)

    return file_path

# =========================
# UI
# =========================
user_input = st.text_area("Paste scam message for FIR generation", height=200)

if st.button("Generate FIR Report"):

    if not user_input.strip():
        st.warning("Please enter a message")
    else:

        fir_content = generate_fir(user_input)

        st.subheader("Generated Complaint")

        st.text(fir_content)

        pdf_path = create_pdf(fir_content)

        with open(pdf_path, "rb") as f:
            st.download_button(
                label="Download FIR PDF",
                data=f,
                file_name="Cyber_FIR_Report.pdf",
                mime="application/pdf"
            )

        st.success("FIR Report generated successfully")